name: SSE CI/CD

on: [push]

jobs:
  style_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Black
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Check code format with Black
      run: |
        python -m black .
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PyTest, Coverage, and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest coverage numpy matplotlib
    - name: Run tests through Coverage + PyTest
      run: |
        python -m coverage run -m pytest .
    - name: Upload Coverage data
      uses: actions/upload-artifact@v2
      with:
        name: coverage-data
        path: .coverage
        retention-days: 1
  coverage_report:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install coverage
      run: |
        python -m pip install --upgrade pip
        pip install coverage
    - name: Download Coverage data
      uses: actions/download-artifact@v2
      with:
        name: coverage-data
    - name: Generate Coverage report
      run: |
        python -m coverage report
        python -m coverage xml
    - name: Upload Coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
        retention-days: 14
        

  

    
